services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: '.env.docker'
        ports:
            - '${APP_PORT}:${APP_PORT}'
        depends_on:
            - db

    db:
        build:
            context: .
        image: postgres
        container_name: postgres_db
        restart: always
        env_file: '.env.docker'
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - '${POSTGRES_PORT}:5432'

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        env_file: '.env.docker'
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        ports:
            - '${PGADMIN_PORT}:80'
        depends_on:
            - db

volumes:
    pgdata:

networks:
    pgnetwork:
